### ISSUE TITLE
SurveyJS - Google Sheets: No data - possibly due to different question types than example

### ISSUE THREAD

**Issue by yogat3ch** [fischerbach/fischerbach.github.io#1]
Hi Rafał,
Thank you for publishing this article! I was trying to come up with a means of implementing SurveyJS just like this over the past few days, and here you post an article detailing how to do it! Quite a synchronicity!
I created and deployed [a survey on my website](http://www.themindful.life/consultation-feedback/) by using the "safe" jQuery syntax such that it works on Wordpress. I've tested the alert method and it outputs the responses to the rating and comment type questions like so:
![image](https://user-images.githubusercontent.com/32208821/102722465-42b8c180-42cf-11eb-9341-2bb149e73035.png)

I've [set up a sheet](https://docs.google.com/spreadsheets/d/1LIwic5pkgyLX0sWlvTBIKCyfr3WRBHJTjifclOBteOA/edit?usp=sharing) and replaced the necessary values in the script below. I've published as a web app with "Anyone, even anonymous" publishing permissions. 

However, I'm not getting any data populating the sheet. 

I think it might have to do with the Rating & Comment question types not being supported yet:

>//TODO: Support other types of questions

and the headers not matching `datetime` or `raw_data`, so the conditional opts for the final `else` statement only suited for multiple choice questions - so the sheet reports back with an error:

![image](https://user-images.githubusercontent.com/32208821/102722907-5580c580-42d2-11eb-82ba-a9185cab626b.png)

The JSON payload looks like this:
![image](https://user-images.githubusercontent.com/32208821/102722951-adb7c780-42d2-11eb-84cf-e7eecf8f3bf0.png)

I'm going to see if I can come up with some javascript such that the sheet will accept the data. I'll share them when I complete them. 

The survey has nine main questions named with a single word, with a `-detail` optional question using the same name.

If you have any simple solutions offhand to handle these questions types that would be great!

```
var SHEET_NAME = "raw"; //  Enter sheet name where results will be collected

var SCRIPT_PROP = PropertiesService.getScriptProperties(); // new property service

function doPost(e){
	return handleResponse(e);
}

function handleResponse(e) {
	// The LockService allows you to have only one invocation of the script or portions thereof run at a time.
	// More about: http://googleappsdeveloper.blogspot.co.uk/2011/10/concurrency-and-google-apps-script.html
	var lock = LockService.getPublicLock(); //Public lock locks for any invocation of script.
	lock.waitLock(30000);

	try {
		// Alternatively, you can hard code spreadsheet here
		// eg. SpreadsheetApp.openById("1AcsuboS3xxk0kj02ACcE_j4ASb8GrxyZscTU5IM-wqc")
		var doc = SpreadsheetApp.openById("MYID");
		var sheet = doc.getSheetByName(SHEET_NAME);

		var data = JSON.parse(e.postData.contents);

		var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
		var nextRow = sheet.getLastRow()+1; // get next row
		var row = [];

		for (i in headers){
			if (headers[i] == "datetime"){
				row.push(new Date());
			} 

			else if (headers[i] == "raw_data"){
				row.push(JSON.stringify(data));
			}
			
			else {
				//To support multiple choice question (checkboxes)
				if(Array.isArray(data[headers[i]])) {
					row.push(data[headers[i]].join('|'));
				}else {
					row.push(data[headers[i]]);
				}
				//TODO: Support other types of questions
			}
		}

		sheet.getRange(nextRow, 1, 1, row.length).setValues([row]);
		// return json success results
		return ContentService
			.createTextOutput(JSON.stringify({"result":"success", "row": nextRow}))
			.setMimeType(ContentService.MimeType.JSON);
	} catch (e){
		// if error return this
		return ContentService
			.createTextOutput(JSON.stringify({"result":"error", "error": e}))
			.setMimeType(ContentService.MimeType.JSON);
	} finally {
		//Release public lock from line 19
		lock.releaseLock();
	}
}

function setup() {
	var doc = SpreadsheetApp.getActiveSpreadsheet();
	SCRIPT_PROP.setProperty("key", doc.getId());
}
```

**Comment by fischerbach** [comment]
Probably you make some mistake with App Script project deployment. I used your code on new spreadsheet and work just fine.

**Comment by yogat3ch** [comment]
Hi @fischerbach, thanks for the response! It looks like I accidentally double posted - the issue with updates and final solution is here: #2
